version: '3'

services:
    yarn:
        image: bigdatateam/yarn-notebook:0.3
        volumes:
            - "${PWD}:/home/jovyan/work"
        ports:
            - "8888:8888"
            - "8088:8088"
    hive:
        image: bigdatateam/hive-course2
        volumes:
            - "${PWD}:/home/jovyan/work"
        ports:
            - "8888:8888"
            - "8088:8088"
    spark:
        image: bigdatateam/spark-course1
        volumes:
            - "${PWD}:/home/jovyan/work"
        ports:
            - "8888:8888"
            - "4040:4040"
    spark2:
        image: bigdatateam/spark-course2
        volumes:
            - "${PWD}:/home/jovyan/work"
        ports:
            - "8888:8888"
            - "4040:4040"
    spark3:
        image: bigdatateam/spark-course3
        volumes:
            - "${PWD}:/home/jovyan/work"
        ports:
            - "8888:8888"
            - "4040:4040"
